title: Katherine Barreto # your name (or website title) here
logo: "/images/logo_image.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist with 1+ years of commercial experience in analytics, market research, data management, and strategy, and a diploma in Data Science from IIT Madras.
  <br><br>
  Completed my Undergraduate degree in B.Sc. Economics (Honors) from Symbiosis International University. The degree majorly focused on Mathematics, Statistics, and Econometrics.
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/katherine-barreto-75a5901ba/">View My LinkedIn Profile</a> 

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

